name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x, 19.x, 20.x, 21.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - name: Start server
        run: |
          node dist/Express.js &
          echo $! > .pidfile
        env:
          CI: true
      - name: Wait for server
        run: |
          while ! curl --silent http://localhost:3000; do
            sleep 1
          done
      - run: npm test
      - name: Stop server
        run: |
          kill $(cat .pidfile)
